In [2]:
import duckdb
import pandas as pd

path = "/home/aoxu/projects/VLS-Benchmark-Dataset/plate-vs/VLS_benchmark/chembl_affinity/uniprot_O00255/O00255_chembl_activities_filtered.parquet"
fixed = path.replace(".parquet", ".fixed.parquet")

# 1) Try reading with DuckDB
df_affinity = duckdb.read_parquet(path).df()
print("Read rows:", len(df_affinity))

# 2) Rewrite to a fresh parquet
duckdb.sql(f"""
COPY (SELECT * FROM read_parquet('{path}'))
TO '{fixed}'
(FORMAT PARQUET);
""")
print("Wrote:", fixed)

# 3) Now try pyarrow on the rewritten file
df_affinity2 = pd.read_parquet(fixed, engine="pyarrow")
print("Re-read rows:", len(df_affinity2))

Read rows: 241
Wrote: /home/aoxu/projects/VLS-Benchmark-Dataset/plate-vs/VLS_benchmark/chembl_affinity/uniprot_O00255/O00255_chembl_activities_filtered.fixed.parquet
Re-read rows: 241

In [15]:
df_affinity2

,action_type,activity_comment,activity_id,activity_properties,assay_chembl_id,assay_description,assay_type,assay_variant_accession,assay_variant_mutation,bao_endpoint,...,assay_target_chembl_id,assay_document_chembl_id,assay_src_id,assay_src_assay_id,assay_category,assay_parameters,assay_classifications,assay_variant_sequence,source_uniprot_id,InchiKey
0,None,NaN,12639600,[],CHEMBL2320318,Binding affinity to menin (unknown origin) aft...,B,NaN,NaN,BAO_0000192,...,CHEMBL1615381,CHEMBL2311406,1,525829,NaN,NaN,NaN,NaN,O00255,ZOOBCIOVQOQBKG-XDIGFQIYSA-N
1,None,NaN,12639601,[],CHEMBL2320318,Binding affinity to menin (unknown origin) aft...,B,NaN,NaN,BAO_0000192,...,CHEMBL1615381,CHEMBL2311406,1,525829,NaN,NaN,NaN,NaN,O00255,PZCALYDOLMJZDT-XDIGFQIYSA-N
2,None,NaN,12639602,[],CHEMBL2320318,Binding affinity to menin (unknown origin) aft...,B,NaN,NaN,BAO_0000192,...,CHEMBL1615381,CHEMBL2311406,1,525829,NaN,NaN,NaN,NaN,O00255,OQTOBSXIFPJPQQ-XDIGFQIYSA-N
3,None,NaN,12639603,[],CHEMBL2320318,Binding affinity to menin (unknown origin) aft...,B,NaN,NaN,BAO_0000192,...,CHEMBL1615381,CHEMBL2311406,1,525829,NaN,NaN,NaN,NaN,O00255,TVAINPANFRVZHB-XDIGFQIYSA-N
4,None,NaN,12639604,[],CHEMBL2320318,Binding affinity to menin (unknown origin) aft...,B,NaN,NaN,BAO_0000192,...,CHEMBL1615381,CHEMBL2311406,1,525829,NaN,NaN,NaN,NaN,O00255,OWRVVYJQBVAHMZ-LQWITFIISA-N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
236,"{'action_type': 'INHIBITOR', 'description': 'N...",NaN,25852115,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL5507502,Binding affinity to menin (unknown origin) inc...,B,NaN,NaN,BAO_0000190,...,CHEMBL1615381,CHEMBL5505977,1,None,NaN,NaN,NaN,NaN,O00255,VGZVOSFYAKUYAO-UHFFFAOYSA-N
237,"{'action_type': 'INHIBITOR', 'description': 'N...",NaN,25852116,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL5507502,Binding affinity to menin (unknown origin) inc...,B,NaN,NaN,BAO_0000190,...,CHEMBL1615381,CHEMBL5505977,1,None,NaN,NaN,NaN,NaN,O00255,HNRPGTDGOBOZDJ-UHFFFAOYSA-N
238,"{'action_type': 'INHIBITOR', 'description': 'N...",NaN,25852117,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL5507502,Binding affinity to menin (unknown origin) inc...,B,NaN,NaN,BAO_0000190,...,CHEMBL1615381,CHEMBL5505977,1,None,NaN,NaN,NaN,NaN,O00255,ZLVOKDNPHNGLID-UHFFFAOYSA-N
239,"{'action_type': 'INHIBITOR', 'description': 'N...",NaN,25852118,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL5507502,Binding affinity to menin (unknown origin) inc...,B,NaN,NaN,BAO_0000190,...,CHEMBL1615381,CHEMBL5505977,1,None,NaN,NaN,NaN,NaN,O00255,ZKIBAYDJDZFTQT-UHFFFAOYSA-N
240,"{'action_type': 'INHIBITOR', 'description': 'N...",NaN,25852119,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL5507502,Binding affinity to menin (unknown origin) inc...,B,NaN,NaN,BAO_0000190,...,CHEMBL1615381,CHEMBL5505977,1,None,NaN,NaN,NaN,NaN,O00255,DSWMTMSAWLJZQF-UHFFFAOYSA-N

In [5]:
df_affinity

,action_type,activity_comment,activity_id,activity_properties,assay_chembl_id,assay_description,assay_type,assay_variant_accession,assay_variant_mutation,bao_endpoint,...,assay_target_chembl_id,assay_document_chembl_id,assay_src_id,assay_src_assay_id,assay_category,assay_parameters,assay_classifications,assay_variant_sequence,source_uniprot_id,InchiKey
0,NaN,NaN,12639600,[],CHEMBL2320318,Binding affinity to menin (unknown origin) aft...,B,NaN,NaN,BAO_0000192,...,CHEMBL1615381,CHEMBL2311406,1,525829,NaN,NaN,NaN,NaN,O00255,ZOOBCIOVQOQBKG-XDIGFQIYSA-N
1,NaN,NaN,12639601,[],CHEMBL2320318,Binding affinity to menin (unknown origin) aft...,B,NaN,NaN,BAO_0000192,...,CHEMBL1615381,CHEMBL2311406,1,525829,NaN,NaN,NaN,NaN,O00255,PZCALYDOLMJZDT-XDIGFQIYSA-N
2,NaN,NaN,12639602,[],CHEMBL2320318,Binding affinity to menin (unknown origin) aft...,B,NaN,NaN,BAO_0000192,...,CHEMBL1615381,CHEMBL2311406,1,525829,NaN,NaN,NaN,NaN,O00255,OQTOBSXIFPJPQQ-XDIGFQIYSA-N
3,NaN,NaN,12639603,[],CHEMBL2320318,Binding affinity to menin (unknown origin) aft...,B,NaN,NaN,BAO_0000192,...,CHEMBL1615381,CHEMBL2311406,1,525829,NaN,NaN,NaN,NaN,O00255,TVAINPANFRVZHB-XDIGFQIYSA-N
4,NaN,NaN,12639604,[],CHEMBL2320318,Binding affinity to menin (unknown origin) aft...,B,NaN,NaN,BAO_0000192,...,CHEMBL1615381,CHEMBL2311406,1,525829,NaN,NaN,NaN,NaN,O00255,OWRVVYJQBVAHMZ-LQWITFIISA-N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
236,"{'action_type': 'INHIBITOR', 'description': 'N...",NaN,25852115,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL5507502,Binding affinity to menin (unknown origin) inc...,B,NaN,NaN,BAO_0000190,...,CHEMBL1615381,CHEMBL5505977,1,None,NaN,NaN,NaN,NaN,O00255,VGZVOSFYAKUYAO-UHFFFAOYSA-N
237,"{'action_type': 'INHIBITOR', 'description': 'N...",NaN,25852116,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL5507502,Binding affinity to menin (unknown origin) inc...,B,NaN,NaN,BAO_0000190,...,CHEMBL1615381,CHEMBL5505977,1,None,NaN,NaN,NaN,NaN,O00255,HNRPGTDGOBOZDJ-UHFFFAOYSA-N
238,"{'action_type': 'INHIBITOR', 'description': 'N...",NaN,25852117,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL5507502,Binding affinity to menin (unknown origin) inc...,B,NaN,NaN,BAO_0000190,...,CHEMBL1615381,CHEMBL5505977,1,None,NaN,NaN,NaN,NaN,O00255,ZLVOKDNPHNGLID-UHFFFAOYSA-N
239,"{'action_type': 'INHIBITOR', 'description': 'N...",NaN,25852118,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL5507502,Binding affinity to menin (unknown origin) inc...,B,NaN,NaN,BAO_0000190,...,CHEMBL1615381,CHEMBL5505977,1,None,NaN,NaN,NaN,NaN,O00255,ZKIBAYDJDZFTQT-UHFFFAOYSA-N
240,"{'action_type': 'INHIBITOR', 'description': 'N...",NaN,25852119,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL5507502,Binding affinity to menin (unknown origin) inc...,B,NaN,NaN,BAO_0000190,...,CHEMBL1615381,CHEMBL5505977,1,None,NaN,NaN,NaN,NaN,O00255,DSWMTMSAWLJZQF-UHFFFAOYSA-N

In [6]:
import pandas as pd

path = "/home/aoxu/projects/VLS-Benchmark-Dataset/plate-vs/VLS_benchmark/chembl_affinity/uniprot_O00255/O00255_chembl_activities_filtered.parquet"

df = pd.read_parquet(
    path,
    engine="pyarrow",
    use_legacy_dataset=True,   # key
    use_threads=False          # sometimes helps too
)
print(len(df), df.dtypes.head())

/home/aoxu/miniconda3/envs/plinder/lib/python3.9/site-packages/pandas/io/parquet.py:265: FutureWarning: Passing 'use_legacy_dataset' is deprecated as of pyarrow 15.0.0 and will be removed in a future version.
  pa_table = self.api.parquet.read_table(

OSError: Repetition level histogram size mismatch

In [8]:
import os, traceback
import pandas as pd

path = "/home/aoxu/projects/VLS-Benchmark-Dataset/plate-vs/VLS_benchmark/chembl_affinity/uniprot_O00255/O00255_chembl_activities_filtered.parquet"

print("File size (bytes):", os.path.getsize(path))

def try_read(label, fn):
    print(f"\n--- {label} ---")
    try:
        df = fn()
        print("OK rows:", len(df))
        print(df.dtypes.head(10))
        return df
    except Exception as e:
        print("FAILED:", repr(e))
        traceback.print_exc(limit=3)
        return None

df1 = try_read("pyarrow default", lambda: pd.read_parquet(path, engine="pyarrow"))
df2 = try_read("pyarrow legacy_dataset", lambda: pd.read_parquet(path, engine="pyarrow", use_legacy_dataset=True, use_threads=False))
df3 = try_read("fastparquet default", lambda: pd.read_parquet(path, engine="fastparquet"))
df4 = try_read("fastparquet pandas_nulls=False", lambda: pd.read_parquet(path, engine="fastparquet", pandas_nulls=False))

File size (bytes): 70996

--- pyarrow default ---
FAILED: OSError('Repetition level histogram size mismatch')

--- pyarrow legacy_dataset ---
FAILED: OSError('Repetition level histogram size mismatch')

--- fastparquet default ---
FAILED: TypeError("int() argument must be a string, a bytes-like object or a number, not 'NAType'")

--- fastparquet pandas_nulls=False ---
FAILED: TypeError("to_pandas() got an unexpected keyword argument 'pandas_nulls'")

Traceback (most recent call last):
  File "/tmp/ipykernel_3175483/56730417.py", line 11, in try_read
    df = fn()
  File "/tmp/ipykernel_3175483/56730417.py", line 20, in <lambda>
    df1 = try_read("pyarrow default", lambda: pd.read_parquet(path, engine="pyarrow"))
  File "/home/aoxu/miniconda3/envs/plinder/lib/python3.9/site-packages/pandas/io/parquet.py", line 669, in read_parquet
    return impl.read(
OSError: Repetition level histogram size mismatch
Traceback (most recent call last):
  File "/tmp/ipykernel_3175483/56730417.py", line 11, in try_read
    df = fn()
  File "/tmp/ipykernel_3175483/56730417.py", line 21, in <lambda>
    df2 = try_read("pyarrow legacy_dataset", lambda: pd.read_parquet(path, engine="pyarrow", use_legacy_dataset=True, use_threads=False))
  File "/home/aoxu/miniconda3/envs/plinder/lib/python3.9/site-packages/pandas/io/parquet.py", line 669, in read_parquet
    return impl.read(
OSError: Repetition level histogram size mismatch
Traceback (most recent call last):
  File "/tmp/ipykernel_3175483/56730417.py", line 11, in try_read
    df = fn()
  File "/tmp/ipykernel_3175483/56730417.py", line 22, in <lambda>
    df3 = try_read("fastparquet default", lambda: pd.read_parquet(path, engine="fastparquet"))
  File "/home/aoxu/miniconda3/envs/plinder/lib/python3.9/site-packages/pandas/io/parquet.py", line 669, in read_parquet
    return impl.read(
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NAType'
Traceback (most recent call last):
  File "/tmp/ipykernel_3175483/56730417.py", line 11, in try_read
    df = fn()
  File "/tmp/ipykernel_3175483/56730417.py", line 23, in <lambda>
    df4 = try_read("fastparquet pandas_nulls=False", lambda: pd.read_parquet(path, engine="fastparquet", pandas_nulls=False))
  File "/home/aoxu/miniconda3/envs/plinder/lib/python3.9/site-packages/pandas/io/parquet.py", line 669, in read_parquet
    return impl.read(
TypeError: to_pandas() got an unexpected keyword argument 'pandas_nulls'

In [14]:
import duckdb

path = "/home/aoxu/projects/VLS-Benchmark-Dataset/plate-vs/VLS_benchmark/chembl_affinity/uniprot_O00255/O00255_chembl_activities_filtered.parquet"

duckdb.sql("SELECT COUNT(*) FROM read_parquet(?)", [path]).fetchall()

TypeError: sql(): incompatible function arguments. The following argument types are supported:
    1. (query: object, *, alias: str = '', params: object = None, connection: duckdb.DuckDBPyConnection = None) -> duckdb.duckdb.DuckDBPyRelation

Invoked with: 'SELECT COUNT(*) FROM read_parquet(?)', ['/home/aoxu/projects/VLS-Benchmark-Dataset/plate-vs/VLS_benchmark/chembl_affinity/uniprot_O00255/O00255_chembl_activities_filtered.parquet']

In [ ]:
# Test if the fixed parquet file can be loaded with pd.read_parquet()
import pandas as pd

path = "/home/aoxu/projects/VLS-Benchmark-Dataset/plate-vs/VLS_benchmark/chembl_affinity/uniprot_O00255/O00255_chembl_activities_filtered.parquet"

print("Testing pd.read_parquet() on fixed file...")
df_test = pd.read_parquet(path, engine="pyarrow")
print(f"✓ Successfully loaded {len(df_test)} rows")
print(f"\nDataFrame info:")
print(df_test.info())
print(f"\nFirst few rows:")
df_test.head()